language: python
python:
  - "3.6"
cache: pip

before_install:
  - wget https://github.com/LoSealL/NTIRE2019-Competition-Test/releases/download/data/Test_LR.zip -P data/
  - wget https://github.com/LoSealL/NTIRE2019-Competition-Test/releases/download/data/BenchmarkNoisyBlocksSrgb.zip -P data/

install:
  - pip install -q tensorflow
  - pip install -q https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl

script:
  - unzip -q data/BenchmarkNoisyBlocksSrgb -d data/
  - unzip -q data/Test_LR -d data/Test_LR
  - RSR_TEST_DIR=data/Test_LR
  - RSR_SAVE_DIR=results/rsr
  # Only for debug
  - _PATCH_SIZE=64
  - _STRIDE=64
  - . one_click_ntire19_rsr.sh
  - DRN_TEST_MAT=data/BenchmarkNoisyBlocksSrgb/BenchmarkNoisyBlocksSrgb.mat
  - DRN_SAVE_DIR=results/drn
  - . one_click_ntire19_drn.sh
